CREATE TABLE IF NOT EXISTS "User"(
	"Id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"UserName" TEXT UNIQUE,
	"Password" TEXT
);

CREATE TABLE IF NOT EXISTS "Group"(
	"Id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"Name" TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS "AppRole"(
	"Id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"Name" TEXT UNIQUE,
	"Label" TEXT,
  "Image" TEXT,
  "GroupId" INTEGER REFERENCES "Group"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserGroup"(
	"Id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"UserId" INTEGER REFERENCES "Group"("Id") ON DELETE CASCADE,
	"GroupId" INTEGER REFERENCES "Group"("Id") ON DELETE CASCADE,
  UNIQUE ("UserId", "GroupId")
);
